/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.pattern;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PatternStandaloneSetup extends PatternStandaloneSetupGenerated {

	public static void doSetup() {
		new PatternStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
