/*
 * generated by Xtext 2.38.0
 */
package org.example.pattern.ide;

import org.xtext.example.pattern.ide.AbstractPatternIdeModule;

/**
 * Use this class to register ide components.
 */
public class PatternIdeModule extends AbstractPatternIdeModule {
}
