/*
 * generated by Xtext 2.38.0
 */
package org.example.pattern;

import org.xtext.example.pattern.AbstractPatternRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PatternRuntimeModule extends AbstractPatternRuntimeModule {
}
