/*
 * generated by Xtext 2.38.0
 */
package org.example.pattern.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PatternUiModule extends AbstractPatternUiModule {

	public PatternUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
