/*
 * generated by Xtext 2.38.0
 */
package org.example.pattern.scoping;

import org.xtext.example.pattern.scoping.AbstractPatternScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class PatternScopeProvider extends AbstractPatternScopeProvider {

}
