/*
 * generated by Xtext 2.38.0
 */
package org.xtext.example.pattern.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.pattern.PatternRuntimeModule;
import org.xtext.example.pattern.PatternStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PatternIdeSetup extends PatternStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PatternRuntimeModule(), new PatternIdeModule()));
	}
	
}
