/*
 * generated by Xtext 2.38.0
 */
package org.example.pattern.validation;

import org.xtext.example.pattern.validation.AbstractPatternValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class PatternValidator extends AbstractPatternValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					PatternPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
